### ISSUE TITLE
Quenching Model Default Value is Outside of Allowed Range

### ISSUE THREAD

**Issue by JosephWick** [ArgonneCPAC/diffsmhm#15]
`diffsmhm/galhalo_models/sigmoid_quenching.py`, line 22. Default value for `fq_sat_tinfall_k` is $10^{0.5} \approx 3.16$, while allowed range is [0,2]

**Comment by aphearin** [comment]
This default value is reasonable. I think the allowed range should be more like [0.2, 5.0].

**Comment by aphearin** [comment]
Well, do be careful however about whether the parameter that is actually being _varied_ is linear or logarithmic. The range where you expect $k$ to vary is $0.2\lesssim k\lesssim 5,$ but if we write $k=10^{\rm lgk},$ then $-0.7\lesssim{\rm lgk}\lesssim0.7.$

**Comment by beckermr** [comment]
Yep. We need to deal with the bounding in the hmc stuff and will take a close look.
